export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST"
export const GET_CUSTOMER_ORDERS = "GET_CUSTOMER_ORDERS"
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"
export const GET_SESSION = "GET_SESSION"
